version: '3.3'
services:
  mysqldb:
    image: mysql:5.7

    container_name: mysql
    ports:
      - "3305:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: "stationski"
      MYSQL_ROOT_HOST: "%"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost" ]
      timeout: 20s
      retries: 10
    restart: always
    ulimits:
      nofile:
        soft: 65536
        hard: 65536


  spring-application:
    image: nedrabenyoussef/skier
    restart: on-failure
    ports:
      - "8089:8089"
    depends_on:
      - mysqldb
    environment:
      SPRING_APPLICATION_JSON: '{
           "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/stationSki?createDatabaseIfNotExist=true",
           "spring.datasource.username" : "root",
           "spring.datasource.password" : "",
           "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
           "spring.jpa.hibernate.ddl-auto" : "update"
         }'

      stdin_open: true
      tty: true
      user: root

volumes:
  db: