version: '3.3'

services:
  mysql:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: stationSki
    ports:
      - 3309:3306  # Port de la base de données MySQL
    volumes:
      - db:/var/lib/mysql

  nedra-app:
    depends_on:
      - mysql
    image: nedra01/skier:1.0
    # L'image Docker de votre application
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysql:3306/stationSki?createDatabaseIfNoExist=true",
        "spring.datasource.username": "root",  
        "spring.datasource.password": null,
        "spring.jpa.hibernate.ddl-auto": "update",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect"
      }'
    stdin_open: true
    tty: true
volumes:
  db: